config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to:"homes#top"
  resources:users, only:[:show, :edit, :update, :destroy]
  resources:posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  validates:title, presence:true
  validates:url, presence:true

  enum category: { work: 0, hobby: 1 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :posts, dependent: :destroy
        
        validates:name, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    # signinした後の遷移先
    root_path
  end

  def after_sign_out_path_for(resource)
    # signoutした後の遷移先
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to user_path(@post.user)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :category)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = User.find(params[:id])
  @all_posts = @user.posts
  @work_posts = @all_posts.where(category: "work")
  @hobby_posts = @all_posts.where(category: "hobby")
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def
  user_params
  params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="conrtainer">
  <h1 class="text-center mt-4 mb-4">Groove</h1>
</div>

<!-- Slider main container -->
<div class="swiper">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">
    <!-- Slides -->
    <div class="swiper-slide">
      <div class="slide-content">
        <%= image_tag 'night-sky-g97827c35f_1280.jpg', class: 'img-fluid mv' %>
        <div class="slide-text">
          <h2 class="mb-5">About</h2>
          <p>作業をしていくうちにタブって多くなりませんか。</p>
          <p>タブを消してしまうと見たい時にどのサイトのものかわからなくなってしまう時ありませんか。</p>
          <p>検索していると解決策を投稿している人と共通点が多いな。と思うことありませんか。</p>
          <p>このサイトで似たもの同士を見つけることで</p>
          <p>タブを整理しながら,問題をすぐに見つけられる可能性があります。</p>
          <p>”情報”による循環（groove）を見つけてみませんか？</p>
        </div>
      </div>
    </div>
    <div class="swiper-slide">
      <div class="slide-content">
        <%= image_tag 'galaxy-gd1e407e2b_1280.jpg', class: 'img-fluid mv' %>
        <div class="slide-text">
          <h2>ここ</h2>
          <p>ここにも文字を配置する</p>
        </div>
      </div>
    </div>


  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mb-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p class="mt-4">CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="openbtn"><span></span><span></span><span></span></div>
  <nav id="g-nav">
  <div id="g-nav-list"><!--ナビの数が増えた場合縦スクロールするためのdiv※不要なら削除-->
    <ul>
        <% if user_signed_in? %>

          <li>
            <%= link_to "About", root_path %>
          </li>
          <li>
            <%= link_to "Trend", posts_path %>
          </li>
          <li>
            <%= link_to "My Page", user_path(current_user) %>
          </li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "About", root_path %>
          </li>
          <li>
            <%= link_to "Log in", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groove</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main style="padding-bottom: 80px">
      <%= yield %>
    </main>
    <div class="footer">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_edit.html.erb
<h1 class="aaa">Posts#edit</h1>
<p class="aaa">Find me in app/views/posts/edit.html.erb</p>

app/views/posts/_index.html.erb
<% posts.each do |obj| %>
  <div class="col-6 mt-3">
    <div class="card">
      <div class="card-body text-center">
        <div class="d-flex justify-content-end">
          <% if current_user.id == obj.user.id %>
           <%= link_to post_path(obj), method: :delete, class: "mr-2" do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
            <%= link_to edit_post_path(obj) do %>
              <i class="fas fa-cog"></i>
            <% end %>
          <% end %>
        </div>
        <h5 class="card-title text-center">
          <% if obj.title.length > 13 %>
            <%= obj.title.slice(0,13) %> ...
          <% else %>
            <%= obj.title %>
          <% end %>
        </h5>
        <p class="card-text">
          <span class="ellipsis-text" data-full-text="<%= obj.url %>">
            <% if obj.url.length > 31 %>
              <%= obj.url.slice(0,31) %> ...
            <% else %>
              <%= obj.url %>
            <% end %>
          </span>
        </p>
        <small class="info-user d-flex justify-content-end">#<%= link_to obj.user.name, user_path(obj.user.id) %></small>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h2 class="text-center mt-5">編集</h2>
  <div class="row">
    <div class="mx-auto d-flex justify-content-center mt-5">
      <%= form_with model: @post, method: :patch, local:true do |f| %>
        <div class="form-group">
          <%= f.label:title %>
          <%= f.text_field:title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label:url %>
          <%= f.text_area:url, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "編集", class: "btn btn-outline-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h2 class="text-center mt-5">Trend</h2>
  <div class="row mx-auto d-flex justify-content-center mt-5">
    <%= render 'posts/index', posts: @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
<h2 class="text-center mt-5">New Card</h2>
        <div class="mt-5 mx-auto d-flex justify-content-center">
            <%= form_with model:@post, local:true, class: "col-6" do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :url %>
                    <%= f.text_area :url, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :category %>
                    <%= f.select :category, Post.categories.keys, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.submit class: "btn btn-outline-secondary" %>
                </div>
            <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h2 class="text-center mt-5"><%= @user.name %></h2>
    
<div class="container">
    <div class="row">
        <div class="col-12">
            <%= form_with model:@user, local:true |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :introduce %>
                    <%= f.text_area :introduce %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="col-12 ">
	<h2 class="text-center mt-5"><%= @user.name %>
		<%= link_to edit_user_path, class: "btn btn-outline-secondary  ml-5" do %>
			<i class="fas fa-user-circle"></i>
		<% end %>
	</h2>
</div>

<div class="wrapper mt-5">
  <ul class="col-12 tab">
    <li><a href="#all">All</a></li>
    <li><a href="#work">WORK</a></li>
    <li><a href="#hobby">HOBBY</a></li>
  </ul>

  <div id="all" class="area">
  	<div class="row">
    	<%= render "posts/index", posts: @all_posts %>
  	</div>
  </div>
  <div id="work" class="area">
  	<div class="row">
    	<%= render "posts/index", posts: @work_posts %>
  	</div>
  </div>
  <div id="hobby" class="area">
  	<div class="row">
    	<%= render "posts/index", posts: @hobby_posts %>
    </div>
  </div>
</div>

<script>
 function GethashID (hashIDName){
	if(hashIDName){
		//タブ設定
		$('.tab li').find('a').each(function() { //タブ内のaタグ全てを取得
			var idName = $(this).attr('href'); //タブ内のaタグのリンク名（例）#lunchの値を取得
			if(idName == hashIDName){ //リンク元の指定されたURLのハッシュタグ（例）http://example.com/#lunch←この#の値とタブ内のリンク名（例）#lunchが同じかをチェック
				var parentElm = $(this).parent(); //タブ内のaタグの親要素（li）を取得
				$('.tab li').removeClass("active"); //タブ内のliについているactiveクラスを取り除き
				$(parentElm).addClass("active"); //リンク元の指定されたURLのハッシュタグとタブ内のリンク名が同じであれば、liにactiveクラスを追加
				//表示させるエリア設定
				$(".area").removeClass("is-active"); //もともとついているis-activeクラスを取り除き
				$(hashIDName).addClass("is-active"); //表示させたいエリアのタブリンク名をクリックしたら、表示エリアにis-activeクラスを追加
			}
		});
	}
}

//タブをクリックしたら
$('.tab a').on('click', function() {
	var idName = $(this).attr('href'); //タブ内のリンク名を取得
	GethashID (idName);//設定したタブの読み込みと
	return false;//aタグを無効にする
});


// 上記の動きをページが読み込まれたらすぐに動かす
$(window).on('load', function () {
    $('.tab li:first-of-type').addClass("active"); //最初のliにactiveクラスを追加
    $('.area:first-of-type').addClass("is-active"); //最初の.areaにis-activeクラスを追加
	var hashName = location.hash; //リンク元の指定されたURLのハッシュタグを取得
	GethashID (hashName);//設定したタブの読み込み
});

</script>